import React from 'react';
import { Lightbulb, Sparkles, CheckCircle2, ArrowRight } from 'lucide-react';
import { useToast } from '../../context/ToastContext';

import { ApiService } from '../../services/api';

export const RecommendationsPage: React.FC = () => {
  const { showToast } = useToast();
  const [recommendations, setRecommendations] = React.useState<any[]>([]);
  const [loading, setLoading] = React.useState<boolean>(true);

  React.useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        const data = await ApiService.get('/ai/recommendations');
        if (data && data.recommendations && data.recommendations.length > 0) {
          setRecommendations(data.recommendations);
        } else {
          setRecommendations([
            {
              id: 'rec_default_1',
              title: 'Optimize Study Duration Blocks',
              category: 'Study Strategy',
              impact: 'High Impact (+12% Focus Score)',
              description: 'Structuring study sessions into 50-minute focus blocks with 10-minute breaks preserves peak flow and prevents fatigue.',
              created_at: 'Today'
            }
          ]);
        }
      } catch {
        // Fallback
      } finally {
        setLoading(false);
      }
    };
    fetchRecommendations();
  }, []);

  return (
    <div className="space-y-6 pb-12">
      <div>
        <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
          <Lightbulb className="w-6 h-6 text-amber-400" />
          AI Recommendations & Wellbeing Assistant
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Personalized actionable tips generated by StudIQ AI engines based on digital behavior and academic performance.
        </p>
      </div>

      <div className="space-y-4">
        {recommendations.map((rec) => (
          <div key={rec.id} className="glass-card rounded-2xl p-6 border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-mono text-brand-400 font-bold uppercase">{rec.category}</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-semibold">
                  {rec.impact}
                </span>
              </div>
              <h3 className="text-base font-bold text-slate-100 mb-1">{rec.title}</h3>
              <p className="text-xs text-slate-300 max-w-2xl leading-relaxed">{rec.description || rec.text}</p>
              <span className="text-[10px] text-slate-500 font-mono mt-2 block">{rec.created_at || rec.date || 'Today'}</span>
            </div>

            <button
              onClick={() => showToast(`Applied recommendation: '${rec.title}'`, 'success')}
              className="bg-brand-600/20 hover:bg-brand-600/30 text-brand-300 border border-brand-500/30 font-semibold text-xs py-2 px-4 rounded-xl flex items-center justify-center gap-1.5 transition whitespace-nowrap"
            >
              Apply Tip <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
