import React from 'react';
import { Lightbulb, Sparkles, CheckCircle2, ArrowRight } from 'lucide-react';
import { useToast } from '../../context/ToastContext';

export const RecommendationsPage: React.FC = () => {
  const { showToast } = useToast();

  const recommendations = [
    {
      id: 1,
      title: 'Optimize Study Duration Blocks',
      category: 'Productivity Engine',
      impact: 'High Impact (+15% Focus)',
      text: 'You achieved peak flow state during 50-minute Pomodoro sessions. Keep taking 10-minute movement breaks to prevent late-afternoon fatigue.',
      date: 'Today'
    },
    {
      id: 2,
      title: 'Set Entertainment Time Limit',
      category: 'Behavior Classifier',
      impact: 'Medium Impact',
      text: 'YouTube usage increased by 25 minutes during late evening research hours. Enable automatic app blockers after 10 PM.',
      date: 'Yesterday'
    },
    {
      id: 3,
      title: 'Course Attendance Threshold Warning',
      category: 'Academic Predictor',
      impact: 'Critical Alert',
      text: 'CS302 lecture attendance is near the 85% requirement boundary. Attend upcoming Friday lectures to secure midterm exam eligibility.',
      date: '3 Days Ago'
    }
  ];

  return (
    <div className="space-y-6 pb-12">
      <div>
        <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
          <Lightbulb className="w-6 h-6 text-amber-400" />
          AI Recommendations & Wellbeing Assistant
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Personalized actionable tips generated by StudIQ AI engines based on digital behavior and academic performance.
        </p>
      </div>

      <div className="space-y-4">
        {recommendations.map((rec) => (
          <div key={rec.id} className="glass-card rounded-2xl p-6 border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-mono text-brand-400 font-bold uppercase">{rec.category}</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-semibold">
                  {rec.impact}
                </span>
              </div>
              <h3 className="text-base font-bold text-slate-100 mb-1">{rec.title}</h3>
              <p className="text-xs text-slate-300 max-w-2xl leading-relaxed">{rec.text}</p>
              <span className="text-[10px] text-slate-500 font-mono mt-2 block">{rec.date}</span>
            </div>

            <button
              onClick={() => showToast(`Applied recommendation: '${rec.title}'`, 'success')}
              className="bg-brand-600/20 hover:bg-brand-600/30 text-brand-300 border border-brand-500/30 font-semibold text-xs py-2 px-4 rounded-xl flex items-center justify-center gap-1.5 transition whitespace-nowrap"
            >
              Apply Tip <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
